Update software_licenses.md
madetech/handbook pull request #690
Opened 2022-09-15 09:22 UTC by NinaPinPeople

New paragraph at the bottom of the page. Updated to reflect access to assistive technology software following discussion with ED&I community group and a number of requests to Ops and People team.

2022-09-15 09:23 UTC, NinaPinPeople commented
@sam-p87 @JillKittos @yaseminercan - could you take a look at this request please when you get a sec and ensure you're happy with it? Thanks.

2022-09-15 09:27 UTC, owenblacker requested changes
There’s a couple of typos here (line 40: `get in touh` should be `get in touch`, line 42 has an extra space before the closing asterisk-pair), but the wording looks great to me.

2022-09-15 12:29 UTC, sam-p87 reviewed
Overall this looks fine to me, though not sure we need to surface the stuff about what's free vs. paid here (unless there was some rationale for doing that?) - think I'd prefer to condense that into something a bit simpler along the lines of:
- Please contact the Ops team for guidance on what assistive technology we already have available
- We'll consider adding new tools to our approved list where existing options don't meet needs

Any views?

2022-09-15 18:50 UTC, NinaPinPeople commented
Comfortable with that @sam-p87 - main reason re free v paid was confirming that the default will be to the readily available free licences and that we'll have a method for assessing how to allocate corporate licences...

2022-09-15 19:13 UTC, yaseminercan commented
I'm unclear on what I have to pay for and from what. The last point makes me think that in some cases I may have to pay for a license from my work from home budget but it wasnt specifically mentioned.
Otherwise looks good to me

2022-09-16 11:06 UTC, NinaPinPeople commented
Additional context @sam-p87 - we have limited business licences in place as it stands, we have had a fair few requests in the last few months,  we haven't got any formal method for determining additional needs that may require more than a basic/free package but are liaising with Occ Health on this and so we thought something that confirmed it won't be an automatic provision in the interim might be useful?

2023-03-03 08:53 UTC, NinaPinPeople commented
@sampaice-MT I've proposed a change here having reviewed with Jill. Could you check and assuming all happy, push to live please?

2023-03-03 09:00 UTC, sampaice-MT approved these changes

2025-04-15 11:46 UTC, WillGibson commented
Closing stale pull request.

2025-04-15 11:46 UTC, closed without merging